# encoding: utf-8

task :default do
  sh 'rake -T'
end

desc 'Build jenkins base image (LDAP+systemd)'
task :build => [:tar_puppet] do
  sh 'docker build --no-cache -t jenkins:systemd .'
end

desc 'Run the jenkins service on 8080 (systemd)'
task :run do
  sh 'docker run --privileged -d --name jenkins --link ldap:ldap -p 8080:8080 jenkins:systemd'
end

##

desc 'Create puppet.tar.gz from ../../puppet'
task :tar_puppet do
  sh 'tar --directory=../.. -czf- puppet/ > puppet.tar.gz'
end
