# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

# Single VM with LDAP and Jenkins
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'jeffmccune/centos7'

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network 'forwarded_port', guest: 389, host: 20389
  config.vm.network 'forwarded_port', guest: 8080, host: 28080

  config.ssh.forward_agent = true

  # Where the puppet code lives
  config.vm.synced_folder '../puppet', '/puppet'

  config.vm.provider 'vmware_fusion' do |vm|
    vm.vmx['memsize'] = '8192'
    vm.vmx['numvcpus'] = 4
  end

  config.vm.provision 'shell' do |shell|
    shell.inline = 'touch /etc/puppet/hiera.yaml'
  end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision 'puppet' do |puppet|
    puppet.manifests_path = '../puppet/manifests'
    puppet.module_path = '../puppet/modules'
    puppet.manifest_file = 'containerhost.pp'
    puppet.options = '--node_name_value=containerhost'
  end
end
