# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

# Single VM with LDAP and Jenkins
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'jeffmccune/centos7'

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network 'forwarded_port', guest: 389, host: 10389

  config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision 'puppet' do |puppet|
    puppet.manifests_path = '../puppet/manifests'
    puppet.module_path = '../puppet/modules'
    puppet.manifest_file = 'sharedvm.pp'
    puppet.options = '--node_name_value=sharedvm'
  end
end
